# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Azure Pass - Sponsorship(3244b50c-81fc-4251-80c2-f041527ed98e)'
    azureResourceGroup: 'foodyhive'
    kubernetesCluster: 'foodyhive-aks'
    namespace: 'default'
    command: install
    chartType: FilePath
    chartPath: .
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
